version: "3.7"
services:
  openvpn:
    build:
      context: .
      args:
        - SERVER_IP=${SERVER_IP}
    restart: always
    ports:
    - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
    - /etc/openvpn_clients/files:/docker/server/client-configs/files
    - /etc/openvpn_clients/keys:/docker/server/client-configs/keys