#!/bin/bash
set -e

./docker_generate_cert.sh bear
./docker_generate_cert.sh giraffe
./docker_generate_cert.sh capybara
./docker_generate_cert.sh coati
./docker_generate_cert.sh peccary
./docker_generate_cert.sh gemsbok
./docker_generate_cert.sh parakeet
./docker_generate_cert.sh cat
./docker_generate_cert.sh springbok
./docker_generate_cert.sh ox
./docker_generate_cert.sh basilisk
./docker_generate_cert.sh walrus
./docker_generate_cert.sh ram
./docker_generate_cert.sh frog
./docker_generate_cert.sh sheep
./docker_generate_cert.sh fox
./docker_generate_cert.sh pony
./docker_generate_cert.sh chipmunk
./docker_generate_cert.sh gazelle
./docker_generate_cert.sh whale
./docker_generate_cert.sh elephant
./docker_generate_cert.sh musk-ox
./docker_generate_cert.sh gnu
./docker_generate_cert.sh leopard
./docker_generate_cert.sh pig
./docker_generate_cert.sh skunk
./docker_generate_cert.sh puppy
./docker_generate_cert.sh badger
./docker_generate_cert.sh donkey
./docker_generate_cert.sh aoudad
./docker_generate_cert.sh lion
./docker_generate_cert.sh woodchuck
./docker_generate_cert.sh blue_crab
./docker_generate_cert.sh stallion
./docker_generate_cert.sh rhinoceros
./docker_generate_cert.sh mynah_bird
./docker_generate_cert.sh cougar
./docker_generate_cert.sh hyena
./docker_generate_cert.sh highland_cow
./docker_generate_cert.sh reindeer
./docker_generate_cert.sh jaguar
./docker_generate_cert.sh mule
./docker_generate_cert.sh civet
./docker_generate_cert.sh squirrel
./docker_generate_cert.sh hippopotamus
./docker_generate_cert.sh meerkat
./docker_generate_cert.sh ferret
./docker_generate_cert.sh yak
./docker_generate_cert.sh steer
./docker_generate_cert.sh aardvark